version: "3"

services:
  app:
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/react-app"
      - "/react-app/node_modules"
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
