version: "3"
services:
  # app:
  #   build: .
  #   env_file: .env
  #   restart: on-failure
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - database
  #   ports:
  #     - "5000:5000"

  database:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - ./sql/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql

volumes:
    data: